### ISSUE TITLE
Keyboard events are not consumed, conflict with default actions

### ISSUE THREAD

**Issue by kornelski** [speps/tt#1]
I have find-as-you-type enabled in Firefox, and I can't use any keys in this game, because the game doesn't call `event.preventDefault()` on keyboard events that it uses. Without this the browser assumes keyboard is not used by the page, and all key presses can be used for browser shortcuts instead.

**Comment by speps** [comment]
Only the keys used for the game have `preventDefault` called, as https://github.com/speps/tt/blob/master/web/tt.js#L337 shows. I didn't think that would be a problem, I didn't want to remove all inputs from the page but maybe it's the way...

**Comment by speps** [comment]
Do you have an example of a website/game that works for you and doesn't do this behaviour? That would be helpful for me to figure out what is going wrong, I'll also enable this accessiblity feature locally and see.

**Comment by kornelski** [comment]
Ah, sorry. I pressed wrong keys, and confused myself :)
