### ISSUE TITLE
Awesome Blog Series!

### ISSUE THREAD

**Issue by PetarKirov** [speps/tt#2]
I just wanted to share that I enjoyed reading your blog series [0]! Nice work on porting this game to modern D, WebAssembly and even mobile PWA!

0: https://speps.fr/articles/torus-trooper-part1/

**Comment by speps** [comment]
Thanks a lot :) I had a lot of fun doing this project!

PS: feels bad to have to close this issue but it's the GitHub way, thanks again!

**Comment by PetarKirov** [comment]
No worries, I was about to close it myself anyway ;)

**Comment by PetarKirov** [comment]
By the way, I think it would be useful to collect some actionable feedback on areas of improving the language ecosystem, based on your experience. Let me know if you'd like to collaborate on something like that with me :)
